// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using THYLoggerAPI_POSTGRESQL.Context;

#nullable disable

namespace THYLoggerAPI_POSTGRESQL.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("THYLoggerAPI_POSTGRESQL.Model.BosDolu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DollyId")
                        .HasColumnType("integer");

                    b.Property<string>("LoggerId")
                        .HasColumnType("text");

                    b.Property<bool?>("SensorDegeri")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DollyId");

                    b.ToTable("BosDolu", (string)null);
                });

            modelBuilder.Entity("THYLoggerAPI_POSTGRESQL.Model.Dolly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dolly", (string)null);
                });

            modelBuilder.Entity("THYLoggerAPI_POSTGRESQL.Model.Gpsdatum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float?>("Altitude")
                        .HasColumnType("real");

                    b.Property<string>("Course")
                        .HasColumnType("text");

                    b.Property<int>("DollyId")
                        .HasColumnType("integer");

                    b.Property<int?>("Fix")
                        .HasColumnType("integer");

                    b.Property<string>("FixAsString")
                        .HasColumnType("text");

                    b.Property<bool?>("GpsFixAvailable")
                        .HasColumnType("boolean");

                    b.Property<float?>("Hdop")
                        .HasColumnType("real");

                    b.Property<bool?>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<float?>("Latitude")
                        .HasColumnType("real");

                    b.Property<float?>("Longitude")
                        .HasColumnType("real");

                    b.Property<int?>("NumberOfSatellites")
                        .HasColumnType("integer");

                    b.Property<int?>("QualityType")
                        .HasColumnType("integer");

                    b.Property<float?>("SpeedKmh")
                        .HasColumnType("real");

                    b.Property<float?>("SpeedKnots")
                        .HasColumnType("real");

                    b.Property<float?>("SpeedMph")
                        .HasColumnType("real");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DollyId");

                    b.ToTable("Gpsdatum", (string)null);
                });

            modelBuilder.Entity("THYLoggerAPI_POSTGRESQL.Model.Nem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DollyId")
                        .HasColumnType("integer");

                    b.Property<float?>("Nem1")
                        .HasColumnType("real");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DollyId");

                    b.ToTable("Nem", (string)null);
                });

            modelBuilder.Entity("THYLoggerAPI_POSTGRESQL.Model.Sicaklik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DollyId")
                        .HasColumnType("integer");

                    b.Property<float?>("Sicaklik1")
                        .HasColumnType("real");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DollyId");

                    b.ToTable("Sicaklik", (string)null);
                });

            modelBuilder.Entity("THYLoggerAPI_POSTGRESQL.Model.BosDolu", b =>
                {
                    b.HasOne("THYLoggerAPI_POSTGRESQL.Model.Dolly", "Dolly")
                        .WithMany()
                        .HasForeignKey("DollyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dolly");
                });

            modelBuilder.Entity("THYLoggerAPI_POSTGRESQL.Model.Gpsdatum", b =>
                {
                    b.HasOne("THYLoggerAPI_POSTGRESQL.Model.Dolly", "Dolly")
                        .WithMany()
                        .HasForeignKey("DollyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dolly");
                });

            modelBuilder.Entity("THYLoggerAPI_POSTGRESQL.Model.Nem", b =>
                {
                    b.HasOne("THYLoggerAPI_POSTGRESQL.Model.Dolly", "Dolly")
                        .WithMany()
                        .HasForeignKey("DollyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dolly");
                });

            modelBuilder.Entity("THYLoggerAPI_POSTGRESQL.Model.Sicaklik", b =>
                {
                    b.HasOne("THYLoggerAPI_POSTGRESQL.Model.Dolly", "Dolly")
                        .WithMany()
                        .HasForeignKey("DollyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dolly");
                });
#pragma warning restore 612, 618
        }
    }
}
